#!/bin/bash

# User inputs for hostname, username, and swapfile size
clear
/bin/echo -e '\n\n' "\e[1;36mRUNNING IN CHROOT ENVIRONMENT...\e[0m"
echo -e '\n'
read -p "Enter Hostname: " HOSTNAME 
echo -e '\n'
read -p "Enter Username: " USERNAME
echo -e '\n'
read -p "Swapfile size (eg: 2, 4, 8): " SWAPFILE
clear

# Display timezone options and read input
printf '
Africa/Abidjan 
Africa/Casablanca
America/Adak 
America/Los_Angeles 
Antarctica/Casey  
Antarctica/Vostok
Asia/Kolkata 
Asia/Tokyo 
Atlantic/Bermuda 
Atlantic/Reykjavik
Australia/Lord_Howe 
Australia/Melbourne
Europe/Amsterdam 
Europe/Istanbul
Indian/Kerguelen
Indian/Reunion
Pacific/Chuuk 
Pacific/Wake
UTC
'
read -p "Enter Timezone: " TIMEZONE 


# Creating and configuring swapfile
/bin/echo -e '\n\n' "\e[1;32mCREATING SWAPFILE...\e[0m"
echo -e '\n'
dd if=/dev/zero of=/swapfile bs=1G count=${SWAPFILE} status=progress
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo "/swapfile	none	swap	defaults	0 0" >> /etc/fstab

# Configuring system settings
ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
echo en_US ISO-8859-1 >> /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 >> /etc/locale.conf 
echo $HOSTNAME >> /etc/hostname
/bin/echo -e '\n\n' "\e[1;33mENTER ROOT PASSWORD...\e[0m"
echo -e '\n'
passwd 

# Installing necessary packages and configuring system settings
sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 5/' /etc/pacman.conf
pacman -Sy grub efibootmgr networkmanager terminus-font zsh zsh-syntax-highlighting zsh-autosuggestions --needed --noconfirm
echo "FONT=ter-g18b" >> /etc/vconsole.conf
echo "FONT_MAP=8859-2" >> /etc/vconsole.conf
sudo sed -i 's/\(^HOOKS=.*\)filesystems\(.*$\)/\1encrypt filesystems\2/' /etc/mkinitcpio.conf
mkinitcpio -p linux
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB 
grub-mkconfig -o /boot/grub/grub.cfg 

# Re-entering encrypted partition and configuring GRUB
clear && /bin/echo -e '\n\n' "\e[1;32mRE-ENTER THE FOLLOWING PARTITION FOR CHROOT ENVIRONMENT!...\e[0m"
lsblk
echo -e '\n'
read -p "RE-Enter Encrypted partition (eg: sda2, vda2, nvme02): " ECRYPTED_VOLUME
LUKS_UUID=$(blkid -o value -s UUID /dev/$ECRYPTED_VOLUME)
echo $LUKS_UUID
sed -i "/^GRUB_CMDLINE_LINUX=/ s/\"\$/cryptdevice=UUID=${LUKS_UUID}:cryptroot root=\/dev\/mapper\/cryptroot\"/" /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg 
systemctl enable NetworkManager 

# Creating a new user, configuring password, and setting sudo privileges
useradd -mG wheel -s /bin/zsh $USERNAME
/bin/echo -e '\n\n' "\e[1;33mENTER THE USER PASSWORD...\e[0m"
echo -e '\n'
passwd $USERNAME
echo "root ALL=(ALL) ALL 
%wheel ALL=(ALL) ALL 
@includedir /etc/sudoers.d" > /etc/sudoers
sleep 1
exit
